# These are supported funding model platforms

github: [codebytaaron]
patreon:
open_collective:
ko_fi: codebytaaron
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: codebytaaron
thanks_dev:
custom:
  - https://zylos.us
